name: toot
summary: toot - a Mastodon CLI client
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
version: 0.46.0
base: core20

grade: stable
confinement: strict

apps:
  toot:
    command: bin/locales-launch $SNAP/bin/toot
    plugs:
      - network
      - home
      - removable-media
      - desktop

parts:
  locales-launch:
    organize:
      locales-launch: bin/
    plugin: dump
    source: https://github.com/Lin-Buo-Ren/locales-launch-part.git
    source-subdir: launchers
    stage-packages:
    - libc-bin
    - locales
  toot:
    plugin: python
    source: https://github.com/ihabunek/toot.git
