name: toot
summary: toot - a Mastodon CLI client
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
adopt-info: toot
base: core18

grade: stable
confinement: strict

apps:
  toot:
    command: locales-launch $SNAP/bin/toot
    plugs:
      - network
      - home
      - removable-media
      - desktop

parts:
  locales-launch:
    organize:
      locales-launch: bin/
    plugin: dump
    source: https://github.com/Lin-Buo-Ren/locales-launch-part.git
    source-subdir: launchers
    stage-packages:
    - libc-bin
    - locales
  toot:
    plugin: python
    source: https://github.com/ihabunek/toot.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info toot | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags)"
